/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionsort;

import java.util.Random;

public class App {
    

    public static void main(String[] args) {
		System.out.println("hello World");
		int[] insertArray = generateList(100);
		printArray(insertArray);
		insertArray = insertionsort(insertArray);
		printArray(insertArray);
	
	}


	public static int[] generateList(int length){
		Random random = new Random();
		int[] randomNumbers = new int[length];
		for(int i = 0; i<length; i++){
			randomNumbers[i] = random.nextInt(10);
		}

		return randomNumbers;
	}

	public static void printArray(int[] array){
		for(int i = 0; i<array.length; i++){
			System.out.print(array[i] + ",");
		}
		System.out.println();
	}

	public static int[] insertionsort(int[] array){
		int loops = 0;
		int length = array.length;
		for(int i = 0; i < length; i++){
			int largest = 0;
			for(int j = 0; j < length - loops; j++){
				
				if(array[largest] < array[j]){
					largest = j;
				}
				
			}
			loops++;
			int temp = array[length - loops];
			array[length - loops] = array[largest];
			array[largest] = temp;
		}

		return array;



	}


}
