/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lettersincommon;

public class App {


    public static String[] wordlist = {"guyana", "lotion", "chilly", "doggie", "fledgy", "swanky", "crawly", "physic"};
    public static String word = "digger";
    public static int count;
    public static int highest = 0;
    public static String highestWord;
    
    public static void main(String[] args) {
        
        for (String string : wordlist) {
            count = 0;
            for (int i=0; i < string.length(); i++) {
                if(string.contains(String.valueOf(word.charAt(i)))){
                    count++;
                }
            }
            if(count > highest){
                highest = count;
                highestWord = string;
            }
        }

        System.out.println(highestWord);
    }
}
