/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package computergeneratedgraphics;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;

import javax.imageio.ImageIO;
 
public class App {
 
    public static void main(String[] args) throws IOException {
 
        int width = 250;
        int height = 250;
 
        // Constructs a BufferedImage of one of the predefined image types.
        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
 
        // Create a graphics which can be used to draw into the buffered image
        Graphics2D g2d = bufferedImage.createGraphics();
 
			
		for(int i =1; i < width + 1; i++){
			Color randColor = generateRandomColour();
			g2d.setColor(randColor);
			g2d.fillRect(i, i, 255, 255);
			
		}

 
		System.out.println(new Color(bufferedImage.getRGB(3, 3), true).getRed());

		
        // Disposes of this graphics context and releases any system resources that it is using. 
        g2d.dispose();
 
        // Save as PNG
        File file = new File("myimage.png");
        ImageIO.write(bufferedImage, "png", file);
 
 
	}
	


	public static Color generateRandomColour(){

		Random random = new Random();
		return new Color(random.nextInt(256), random.nextInt(256), random.nextInt(256));
	}
 
}