/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package starstrings;

public class App {
    
    public static String message = "The unusually warm weather makes me think of summer. It is hard to stay focused on mundane work.";
    public static final int length = 20;
    public static int pointer = 0;

    public static void main(String[] args) {
        for(int i = 0; i<length + 4; i++){
            System.out.print("*");
        }

        System.out.print("\n");

        while(!(pointer >= message.length() - 1)){

            String line = getPhrase();

            System.out.print("* ");

            System.out.print(line);

            System.out.println(" *");
        }



        for(int i = 0; i<length + 4; i++){
            System.out.print("*");
        }
        System.out.print("\n");

    }

    public static String getPhrase(){
        if(message.length() - pointer < length){
            pointer = message.length();
            return message.substring(pointer, message.length() - 1);
        }

        String tempMessage = message.substring(pointer, clamp(pointer + length, 0, message.length() - 1));
        int end = tempMessage.lastIndexOf(" ");

        tempMessage = tempMessage.substring(0, end);

        pointer += end;

        return tempMessage;
    }

    public static int clamp(int clampedNumber, int lowerClamp, int upperClamp){
        return Math.min(Math.max(clampedNumber, lowerClamp), upperClamp);
    }
}
